/**
 * Writes migrations/0002_seed.sql from fixtures/standard.json.
 * Does not rewrite the fixture — that file is the source of truth.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const products = JSON.parse(readFileSync(join(root, "fixtures/standard.json"), "utf8"));
const now = 1756272000000;

const sql = [
  "-- Generated by scripts/generate-seed.mjs from fixtures/standard.json.",
  "DELETE FROM standard_aliases;",
  "DELETE FROM standard_products;",
  "",
];

for (const p of products) {
  sql.push(
    `INSERT INTO standard_products (sku, canonical_name, uom, list_price, currency, tax_code, version, updated_at) VALUES (${lit(p.sku)}, ${lit(p.canonicalName)}, ${lit(p.uom)}, ${p.listPrice}, ${lit(p.currency)}, ${lit(p.taxCode)}, ${p.version}, ${now});`,
  );
  for (const alias of p.aliases ?? []) {
    sql.push(
      `INSERT INTO standard_aliases (sku, alias, source_doc_id, created_at) VALUES (${lit(p.sku)}, ${lit(alias)}, NULL, ${now});`,
    );
  }
}
sql.push("");

writeFileSync(join(root, "migrations/0002_seed.sql"), sql.join("\n") + "\n");
console.log(`wrote ${products.length} products into migrations/0002_seed.sql`);

function lit(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}
